version: "3"
services:
  web:
    restart: always
    container_name: covidcomplex
    hostname: covidcomplex
    build: .
    volumes:
      - dbv:/data/db
    ports:
      - "8500:80"
    environment:
      - WEB_PORT=8500
volumes:
  dbv:
